# Generated by Django 5.1.15 on 2026-02-28 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING_MODERATION', 'На модерации'), ('PUBLISHED', 'Опубликован'), ('REJECTED', 'Отклонён'), ('ARCHIVED', 'В архиве'), ('BLOCKED_BY_SECURITY', 'Заблокирован (безопасность)'), ('PENDING_PLAGIARISM_REVIEW', 'Проверка плагиата'), ('EMBEDDING_FAILED', 'Ошибка эмбеддинга')], db_index=True, default='DRAFT', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('og_image_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('purchases_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='prompts.prompt')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('user', 'prompt')},
            },
        ),
        migrations.CreateModel(
            name='PromptAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='prompts.prompt')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_access', to='payments.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к промпту',
                'verbose_name_plural': 'Доступы к промптам',
                'indexes': [models.Index(fields=['user', 'prompt'], name='prompts_pro_user_id_203dcd_idx')],
                'unique_together': {('user', 'prompt')},
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['status', 'published_at'], name='prompts_pro_status_ce87b2_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['seller', 'status'], name='prompts_pro_seller__d6387b_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_free', 'status'], name='prompts_pro_is_free_d08c24_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['category', 'status'], name='prompts_pro_categor_4005bd_idx'),
        ),
    ]
