# Generated by Django 5.1.15 on 2026-02-28 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('SUCCESS', 'Оплачен'), ('FAILED', 'Ошибка оплаты'), ('CANCELLED', 'Отменён'), ('REFUNDED', 'Возвращён')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('platform_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('robokassa_inv_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-created_at'],
            },
        ),
    ]
