# Generated by Django 5.1.15 on 2026-02-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='prompts.prompt'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'status'], name='payments_pu_user_id_8e2916_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['prompt', 'status'], name='payments_pu_prompt__fd4ede_idx'),
        ),
    ]
